services:
  redis:
    image: redis:latest

  mongo_db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: books
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      MONGO_URL: mongodb://mongo_admin:password@mongo_db:27017
      REDIS_URL: redis://redis:6379/0
      JWT_SECRET_KEY: lab6-super-secret-change-me
      ACCESS_TOKEN_EXPIRE_MINUTES: 15
      REFRESH_TOKEN_EXPIRE_DAYS: 7
    depends_on:
      - redis
      - mongo_db

volumes:
  mongo_data:
